[package]
name = "gpui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
catppuccin = "1.3.0"
global-hotkey = "0.4.2"
gpui = { git = "https://github.com/zed-industries/zed" }
serde = "1.0.195"
serde_json = "1.0.111"
tokio = { version = "1.36.0", features = ["full"] }
